spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pitches
    password: Api2023*
    username: api
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true



