spring:
  application:
    name: frontend-screens-service
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
server:
  port: 9000
  address: 0.0.0.0
logging:
  level:
    org:
      hibernate: info


# flyway configs