CREATE TABLE IF NOT EXISTS frontend_screens_register
(
    FSR_ID NUMERIC PRIMARY KEY,
    FSR_SCREEN_NAME VARCHAR(200) UNIQUE NOT NULL,
    FSR_TARGET_SYSTEM NUMERIC,
    FSR_SCREEN_FIELDS JSON,
    FSR_DESCRIPTION VARCHAR(400),
    FSR_SHORT_DESCRIPTION VARCHAR(200) UNIQUE NOT NULL,
    FSR_VARIES VARCHAR(1) DEFAULT 'N'
)