CREATE TABLE IF NOT EXISTS SELECT_OPTIONS_PER_FIELD
(
    SOPF_FIELD_ID NUMERIC NOT NULL,
    SOPF_SELECT_OPTION_ID NUMERIC NOT NULL,
    CONSTRAINT SELECT_OPTIONS_PER_FIELD_KEY PRIMARY KEY(SOPF_FIELD_ID, SOPF_SELECT_OPTION_ID)
)